### PR TITLE
Allow Embroider v1 deps; Drop node v10

### PR DESCRIPTION
**Pull request by josemarluedke**
Node 10 is not compatible with embroider v1.

### CODE REVIEW

**Comment by josemarluedke** [comment]
Failing tests are due to Ember v4 requiring ember-auto-import v2. Which can be solved in other PR.

**Comment by cibernox** [comment]
Since that is a different issue I'm going to merge this as is

**Comment by cibernox** [comment]
thanks!

**Comment by cibernox** [comment]
@josemarluedke to clarify, are you upgrading ember-auto-import next?

**Comment by josemarluedke** [comment]
@cibernox PR coming.

**Comment by jamescdavis** [comment]
Can we get a release with this? 🙂

**Comment by josemarluedke** [comment]
I think we can merge #73 and then release it. Looking forward to have a release out as well.

**Comment by lifeart** [comment]
adding more search keywords here, updating to `0.6.0` from `0.5.5` fixes 

```
Build Error (broccoli-persistent-filter:Babel > [Babel: @embroider/macros]) in @embroider/macros/runtime.js

C:\Users\lifeart\Documents\repos\smassetman_spa\smassetman\@embroider\macros\runtime.js: @babel/template placeholder "OPTIONS": Expected string substitution
```

error for me

**Pull request merged**
