### PR TITLE
Stop depending in `@glimmer/syntax`

### PR DESCRIPTION
**Pull request by cibernox**

### CODE REVIEW

**Comment by chancancode** [comment]
@rwjblue r?

**Comment by cibernox** [comment]
I fixed the tests. It still fails in Ember beta and canary, but seems unrelated with this change /cc @chancancode Any idea?

**Comment by chancancode** [comment]
I’ll take a look!

**Comment by chancancode** [comment]
screen shot 2019-02-06 at 5 03 32 pm

Need to investigate more but this is the failure

**Comment by chancancode** [comment]
Stack trace

```
TypeError: Cannot read property 'lastNode' of null
    at UpdatableBlockTracker.lastNode (http://localhost:4200/assets/vendor.js:47343:19)
    at SimpleBlockTracker.lastNode (http://localhost:4200/assets/vendor.js:47343:19)
    at UpdatableBlockTracker.lastNode (http://localhost:4200/assets/vendor.js:47343:19)
    at clear (http://localhost:4200/assets/vendor.js:45863:23)
    at UpdatableBlockTracker.reset (http://localhost:4200/assets/vendor.js:47408:25)
    at TryOpcode.handleException (http://localhost:4200/assets/vendor.js:47844:79)
    at UpdatingVMFrame.handleException (http://localhost:4200/assets/vendor.js:48024:31)
    at UpdatingVM.throw (http://localhost:4200/assets/vendor.js:47771:18)
    at Assert.evaluate (http://localhost:4200/assets/vendor.js:44598:17)
    at UpdatingVM.execute (http://localhost:4200/assets/vendor.js:47754:16)
```

**Comment by chancancode** [comment]
Seems like the problem is that the [first test case](https://github.com/tildeio/ember-element-helper/blob/master/tests/integration/helpers/element-test.js#L61-L67) raised an error during rendering, which left the VM in an inconsistent state. The solution is probably to split each of them up into their own test.

**Comment by chancancode** [comment]
I opened #5 to address the problem. Once that's merged, this can be rebased on top and should make the problem go away. Sorry about that!

**Pull request merged**
