### PR TITLE
Upgrade Ember Auto Import to v2; Refresh other deps

### PR DESCRIPTION
**Pull request by josemarluedke**
It also refresh other deps to latest.

### CODE REVIEW

**Comment by SergeAstapov** [comment]
@josemarluedke FYI looks like `ember-cli-template-lint` should be replaced with `ember-template-lint` v3+ or v4

**Comment by SergeAstapov** [comment]
@josemarluedke FYI now it's probably ember-qunit@4 and may need v5 bump

**Comment by josemarluedke** [comment]
@SergeAstapov @cibernox The failing tests now require the octane mirgation (qunit v5 and etc). Work is in progress in #73.

Can we can this merged and move to that PR next?

**Comment by cibernox** [comment]
One step at a time I guess.

**Pull request merged**
